version: 2

models:
  - name: int_video_events
    description: "Model to calculate the duration per video play action for clients."
    tests:
          - elementary.freshness_anomalies:
                  timestamp_column: created_at  # Mandatory
                  time_bucket:
                    period: hour
                    count: 1  # Detect anomalies for up to 120 days
                  where_expression: "created_at IS NOT NULL"  # Optional filter
    
    columns:
      - name: client_id
        description: "Unique identifier for the device or client."
        tests:
          - not_null
          - elementary.column_anomalies

      - name: media_id
        description: "Unique identifier for the video being played."
        tests:
          - not_null
          - elementary.column_anomalies

      - name: action
        description: "Type of action performed by the user (e.g., 'pause')."
        tests:
          - not_null
          - accepted_values:
              values: ['pause']
              config:
                severity: warn
          - elementary.column_anomalies

      - name: created_at
        description: "Timestamp when the video action occurred (Taipei timezone)."
        tests:
          - not_null

      - name: duration_seconds
        description: "Duration in seconds between consecutive 'pause' actions."
        tests:
          - not_null
          - elementary.column_anomalies:
              anomaly_params:
                method: z_score
                threshold: 3
