dbt_profiles_dir: profiles.yml
monitor:
  slack:
    token: "${{ env.SLACK_API_TOKEN }}"
    channel_name: dbt
    webhook_url: "${{ env.WEBHOOK_URL }}"
  alerts:
    group_by: table  # Group alerts by table name
    include_details: true  # Include details for each alert
    include_summary: true  # Add a summary of alerts in Slack
elementary:
  outputs:
    dev:
      dataset: dcard_app
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ./gcp/dcard-444807-532e508619ed.json
      location: asia-east1
      method: service-account
      priority: interactive
      project: dcard-444807
      threads: 4
      type: bigquery
    postgres_dev:
      type: postgres
      host: localhost   # Replace with your PostgreSQL host, e.g., localhost or an IP address
      user: postgres   # Replace with your PostgreSQL username
      password: postgres  # Replace with your PostgreSQL password
      port: 5433
      dbname: dcard  # Replace with your PostgreSQL database name
      schema: staging  # Schema where dbt will create tables; adjust if needed
      threads: 4
  target: postgres_dev